version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: markdown-table
    versions:
    - 2.0.0
